name: Trigger Amplify Build
on:
  push:
    branches:
      - main
    paths:
      - 'content/blogs/**.md'
      - 'content/case-studies/**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Amplify Webhook
        run: |
          curl -X POST -d {} "https://webhooks.amplify.ap-south-1.amazonaws.com/prod/webhooks?id=174d7453-5d45-4398-8374-58bc7a3dc8e7&token=pbxgzZWeTYZbg1m6qEuK2K7Kja4fPgDHXcuqe6nsA&operation=startbuild" -H "Content-Type:application/json"
